---

- name: HUE
  hosts: localhost
  become: yes
  vars:
    folder: "/var/lidop/hue"

  tasks:
    - name: set docker-compose
      template:
        src: docker-compose.yml.j2
        dest: ./docker-compose.yml

    - name: delete directory
      file:
        path: "{{ folder }}"
        state: absent

    - name: create directory
      file:
        path: "{{ folder }}"
        state: directory
        owner: root
        group: root
        mode: 0777
      when: state == "present"
      
    - name: Copy config
      copy:
        src: config/
        dest: "{{ folder }}"
        mode: 0644
      when: state == "present"

    - name: Update config
      template:
        src: "{{ folder }}/{{ item }}.j2"
        dest: "{{ folder }}/{{ item }}"
      when: state == "present"
      with_items:
        - nodered/flows_cred.json
        - nodered/flows.json

    - name: fix folder permissions
      file:
        path: "{{ folder}}/nodered"
        mode: 0777
        recurse: true
